# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureFunctionBlobQueueTriggerRMConn'
    subscriptionId: '3ba3b1ee-cdf6-4ce2-918d-4346318d33ac'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureRmFunBlobQueueTriggerPipeline-rg'
    location: 'Central US'
    templateLocation: 'Linked artifact'
    csmFile: 'AzureFunBlobQueueTriggerRepo/template.json'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployAzureFunBlobQueueTriggerPipelineTemplate'
    deploymentOutputs: 'DeployAzureFunBlobQueueTriggerPipelineOutput'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml

  displayName: 'Run a multi-line script for AzureFunctionBlobQueueTrigger Pipeline'
